# Generated by Django 2.0.5 on 2018-05-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lock',
            old_name='ip_addr',
            new_name='ip_address',
        ),
    ]
